# Generated by Django 4.0.3 on 2022-04-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physicaltherapist",
            name="account_ptr",
        ),
        migrations.RemoveField(
            model_name="systemadmin",
            name="account_ptr",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
        migrations.DeleteModel(
            name="PhysicalTherapist",
        ),
        migrations.DeleteModel(
            name="SystemAdmin",
        ),
    ]
