# Generated by Django 4.0.3 on 2022-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_physicaltherapistprofile_patientprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="address",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name="physicaltherapistprofile",
            name="address",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
