# Generated by Django 4.0.3 on 2022-06-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_file_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pdf',
            field=models.FileField(upload_to='files/orders/'),
        ),
    ]
