# Generated by Django 4.0.3 on 2022-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_account_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_request',
            name='role',
            field=models.CharField(choices=[('SA', 'System Admin'), ('PT', 'Physical Therapist'), ('P', 'Patient')], default='SA', max_length=2, verbose_name='role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=8),
        ),
    ]
