# Generated by Django 4.0.4 on 2022-05-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_account_request_role_alter_account_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ptr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teleconsultation_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_tc_time', models.DateTimeField(verbose_name='start teleconsultation hours')),
                ('end_tc_time', models.DateTimeField(verbose_name='end teleconsultation hours')),
                ('fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.physicaltherapist')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ptr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_ptr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_clinic_time', models.DateTimeField(verbose_name='start clinic hours')),
                ('end_clinic_time', models.DateTimeField(verbose_name='end clinic hours')),
                ('fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.physicaltherapist')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('teleconsultation', 'teleconsultation'), ('clinical', 'Clinical')], default='teleconsultation', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending', max_length=9)),
                ('patient_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.patient')),
            ],
        ),
    ]
