# Generated by Django 4.0.4 on 2022-05-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_physicaltherapist_teleconsultation_hours_systemadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pt_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.physicaltherapist'),
        ),
    ]
