# Generated by Django 4.0.3 on 2022-06-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webapp.patientprofile'),
        ),
    ]
